# Default configuration for robotic arm trajectory planning

# Environment settings
environment:
  robot: "kuka"  # Using Kuka robot which is included with PyBullet
  render: true
  max_episode_steps: 500
  obstacle_count: 1
  initial_position: [0.1, 0.1, 0.5]  # Good starting position 
  goal_position: [0.3, 0.3, 0.3]  # Easier goal position
  goal_tolerance: 0.1  # Increased tolerance for easier success
  workspace_bounds: [[-0.5, 0.5], [-0.5, 0.5], [0.0, 1.0]]
  
  # Semi-Markov Decision Process (SMDP) settings
  use_smdp: false  # Disable Semi-MDP approach for simplicity
  min_action_duration: 1  # Minimum number of simulation steps per action
  max_action_duration: 10  # Maximum number of simulation steps per action
  sub_step_size: 0.05  # Time step for simulation steps
  
  # Controller settings
  use_mpc: false  # Disable MPC due to CasADi issues, use only RL

# RL algorithm settings
rl:
  algorithm: "ppo"
  policy: "MlpPolicy"
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.05   # Increased to encourage more exploration
  total_timesteps: 200000  # Reduced for quicker testing

# MPC settings
mpc:
  horizon: 10
  dt: 0.1
  q_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # Position weights
  r_weights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]  # Control weights

# Camera settings
camera:
  width: 640
  height: 480
  fov: 60
  near_val: 0.1
  far_val: 10.0
